apiVersion: apps/v1
kind: Deployment
metadata:
  name: service_name
  labels:
    app: service_name

---
apiVersion: v1
kind: Service
metadata:
  name: service_name

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service_name
